[versions]
#resourcesVersion = "0.23.123"
#resourcesVersion = "0.23.135"
#resourcesVersion = "0.23.100"
resourcesVersion = "0.23.140"

[libraries]
resources = { module = "dev.icerock.moko:resources", version.ref = "resourcesVersion" }
resourcesCompose = { module = "dev.icerock.moko:resources-compose", version.ref = "resourcesVersion" }
resourcesTest = { module = "dev.icerock.moko:resources-test", version.ref = "resourcesVersion" }

resourcesGradlePlugin = { module = "dev.icerock.moko:resources-generator", version.ref = "resourcesVersion" }
